pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Test') {
            steps {
                sh 'echo "testing project"'
            }
        }
        stage('Build') {
            steps {
                sh 'echo "building project"'
            }
        }
        stage('Push') {
            steps {
                sh 'echo "pushing project"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "deploying project"'
            }
        }
    }
}