pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "building project"'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "test project"'
            }
        }
    }
}